//! LLM provider layer.
//!
//! One OpenAI-compatible client covers every provider: Ollama and LM Studio
//! locally, OpenRouter in the cloud, and any custom base URL later — they all
//! speak `/v1/chat/completions` (streaming SSE + tool calls) and `/v1/models`.
//!
//! Several providers can be configured at once, and the models the user
//! actually cares about are kept as a *library* of (provider, model) pairs —
//! every model choice in the app (chat, summaries, the fallback chain) points
//! into it. That is what makes a provider's own catalogue browsable but not
//! load-bearing: OpenRouter lists hundreds of models, and none of them should
//! have to be scrolled past to pick the two you use.
//!
//! Config (providers, the library, model choices, spending limits) lives in
//! the `settings` table under the `"llm"` key, written by the frontend and
//! read here headlessly via sqlx. API keys never touch the database or the
//! frontend: they live in the macOS keychain, keyed by provider id, and the
//! commands below only ever return booleans about them.
//!
//! Every model call records a row in `llm_usage`; `check_budget` sums the
//! current calendar month before each call and refuses when a user-set cap is
//! reached. OpenRouter reports real cost when asked (`usage.include`); local
//! providers record NULL cost.
//!
//! Streaming stays on ureq (the crate's only HTTP client): SSE is just lines
//! on a reader. The agent sets a read timeout but no overall timeout — local
//! models legitimately pause between chunks. A hung provider therefore blocks
//! its thread until the read timeout; cancellation (later phases) takes
//! effect between reads.

use std::io::{BufRead, BufReader};
use std::time::Duration;

use serde::{Deserialize, Serialize};
use sqlx::{Row, SqlitePool};
use tauri::{AppHandle, Emitter};

/// Keychain service name; the account is the provider id.
const KEYCHAIN_SERVICE: &str = "com.tchan.oculus.llm";

/// How many models the fallback chain holds. Small on purpose: it is a list
/// to read at a glance and reorder by hand, not a routing table.
pub const MAX_FALLBACKS: usize = 5;

const CONNECT_TIMEOUT: Duration = Duration::from_secs(10);
/// Between-chunk allowance while streaming. Generous: a local model loading
/// into memory can sit silent well past a minute before the first token.
const READ_TIMEOUT: Duration = Duration::from_secs(120);
const MODELS_TIMEOUT: Duration = Duration::from_secs(20);

// ── Config ───────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct LlmLimits {
    pub monthly_usd: Option<f64>,
    pub monthly_tokens: Option<i64>,
}

/// One configured endpoint. `id` is generated by the frontend, stable for the
/// provider's lifetime, and doubles as its keychain account — which is why it
/// is never regenerated on edit.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct ProviderConfig {
    pub id: String,
    /// 'ollama' | 'lmstudio' | 'openrouter' | 'opencode-go' | 'custom'
    pub kind: String,
    /// What the user calls it — two OpenRouter accounts need telling apart.
    pub label: String,
    /// Overrides the kind's default when set (custom requires it).
    pub base_url: Option<String>,
}

impl ProviderConfig {
    /// The endpoint's root, with no `/v1` on the end — `api_url` adds that.
    /// Providers advertise their URL both ways (Ollama's docs say
    /// `http://localhost:11434/v1`), so a pasted `/v1` suffix is trimmed
    /// rather than doubled: `/v1/v1/models` is a 404 on every provider.
    pub fn base_url(&self) -> Result<String, String> {
        let url = match self.base_url.as_deref().filter(|s| !s.trim().is_empty()) {
            Some(u) => u.trim().to_string(),
            None => match self.kind.as_str() {
                "ollama" => "http://localhost:11434".into(),
                "lmstudio" => "http://localhost:1234".into(),
                "openrouter" => "https://openrouter.ai/api".into(),
                "opencode-go" => "https://opencode.ai/zen/go".into(),
                other => return Err(format!("provider '{other}' needs a base URL")),
            },
        };
        let url = url.trim_end_matches('/');
        Ok(url.strip_suffix("/v1").unwrap_or(url).trim_end_matches('/').to_string())
    }

    fn api_url(&self, path: &str) -> Result<String, String> {
        Ok(format!("{}/v1{path}", self.base_url()?))
    }

    fn api_key(&self) -> Option<String> {
        stored_api_key(&self.id)
    }
}

/// A model in the library: which endpoint serves it, and its id there. The
/// same model id can appear under two providers, so neither half identifies
/// it alone.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct ModelRef {
    pub provider_id: String,
    pub model: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct LlmConfig {
    pub providers: Vec<ProviderConfig>,
    /// The user's curated models — everything selectable anywhere in the app.
    pub library: Vec<ModelRef>,
    pub chat_model: Option<ModelRef>,
    /// Tried in order when the preferred model cannot run; at most
    /// `MAX_FALLBACKS`, ordered by the user.
    pub fallbacks: Vec<ModelRef>,
    pub limits: LlmLimits,
}

impl LlmConfig {
    pub fn provider(&self, id: &str) -> Option<&ProviderConfig> {
        self.providers.iter().find(|p| p.id == id)
    }
}

/// A model call's endpoint and model id, after the fallback chain has run.
pub struct Resolved {
    pub provider: ProviderConfig,
    pub model: String,
}

fn default_label(kind: &str) -> String {
    match kind {
        "ollama" => "Ollama",
        "lmstudio" => "LM Studio",
        "openrouter" => "OpenRouter",
        "opencode-go" => "OpenCode Go",
        _ => "Custom",
    }
    .to_string()
}

/// Read config written before multi-provider support — one provider, three
/// bare model names. Upgraded in memory on every read; the first edit in
/// Settings rewrites the row in the new shape. The synthesised provider keeps
/// its id equal to the old provider name so the keychain entry still resolves.
fn migrate_legacy(v: &serde_json::Value) -> LlmConfig {
    let kind = v["provider"].as_str().unwrap_or("ollama").to_string();
    let provider = ProviderConfig {
        id: kind.clone(),
        label: default_label(&kind),
        kind,
        base_url: v["baseUrl"].as_str().map(str::to_string),
    };
    let model_ref = |key: &str| {
        v[key]
            .as_str()
            .filter(|s| !s.trim().is_empty())
            .map(|m| ModelRef { provider_id: provider.id.clone(), model: m.to_string() })
    };
    // `summaryModel` was the automations digest's model. The feature is gone,
    // so it has no slot — but it still seeds the library, or upgrading would
    // silently drop a model the user had curated.
    let (chat, summary, fallback) =
        (model_ref("chatModel"), model_ref("summaryModel"), model_ref("fallbackModel"));

    let mut library: Vec<ModelRef> = Vec::new();
    for m in [&chat, &summary, &fallback].into_iter().flatten() {
        if !library.contains(m) {
            library.push(m.clone());
        }
    }

    LlmConfig {
        providers: vec![provider],
        library,
        chat_model: chat,
        fallbacks: fallback.into_iter().collect(),
        limits: serde_json::from_value(v["limits"].clone()).unwrap_or_default(),
    }
}

/// Open the shared database the same way the CLI does — no AppHandle, so
/// later phases can run headless.
pub async fn open_pool() -> Result<SqlitePool, String> {
    let path = crate::paths::db_path(&crate::paths::data_dir());
    if !path.exists() {
        return Err(format!("no database at {}", path.display()));
    }
    crate::retrieval::pool(&path).await
}

pub async fn load_config(pool: &SqlitePool) -> Result<LlmConfig, String> {
    let row = sqlx::query("SELECT value FROM settings WHERE key = 'llm'")
        .fetch_optional(pool)
        .await
        .map_err(|e| e.to_string())?;
    let Some(r) = row else { return Ok(LlmConfig::default()) };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&r.get::<String, _>("value")) else {
        return Ok(LlmConfig::default());
    };
    // A row with no `providers` array predates multi-provider config.
    if v.get("providers").and_then(|p| p.as_array()).is_none_or(|a| a.is_empty()) {
        return Ok(migrate_legacy(&v));
    }
    Ok(serde_json::from_value(v).unwrap_or_default())
}

// ── Keychain ─────────────────────────────────────────────────────────────────

fn keychain(provider: &str) -> Result<keyring::Entry, String> {
    keyring::Entry::new(KEYCHAIN_SERVICE, provider).map_err(|e| e.to_string())
}

fn stored_api_key(provider: &str) -> Option<String> {
    keychain(provider).ok()?.get_password().ok()
}

// ── Usage + budget ───────────────────────────────────────────────────────────

#[derive(Debug, Clone, Default, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Usage {
    pub prompt_tokens: i64,
    pub completion_tokens: i64,
    pub cost_usd: Option<f64>,
}

pub async fn record_usage(
    pool: &SqlitePool,
    provider: &str,
    model: &str,
    purpose: &str,
    usage: &Usage,
    chat_id: Option<i64>,
) -> Result<(), String> {
    sqlx::query(
        "INSERT INTO llm_usage (provider, model, purpose, prompt_tokens, completion_tokens, cost_usd, chat_id)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
    )
    .bind(provider)
    .bind(model)
    .bind(purpose)
    .bind(usage.prompt_tokens)
    .bind(usage.completion_tokens)
    .bind(usage.cost_usd)
    .bind(chat_id)
    .execute(pool)
    .await
    .map_err(|e| e.to_string())?;
    Ok(())
}

/// Refuse a call once either monthly cap is reached. Called before every
/// model turn, so a long agent run stops at the cap rather than after it.
pub async fn check_budget(pool: &SqlitePool, cfg: &LlmConfig) -> Result<(), String> {
    if cfg.limits.monthly_usd.is_none() && cfg.limits.monthly_tokens.is_none() {
        return Ok(());
    }
    let row = sqlx::query(
        "SELECT COALESCE(SUM(prompt_tokens + completion_tokens), 0) AS tokens,
                COALESCE(SUM(cost_usd), 0.0) AS usd
         FROM llm_usage
         WHERE created_at >= strftime('%Y-%m-01 00:00:00', 'now')",
    )
    .fetch_one(pool)
    .await
    .map_err(|e| e.to_string())?;
    let tokens: i64 = row.get("tokens");
    let usd: f64 = row.get("usd");

    if let Some(cap) = cfg.limits.monthly_usd {
        if usd >= cap {
            return Err(format!(
                "Monthly spending limit reached (${usd:.2} of ${cap:.2}) — raise it in Settings → AI"
            ));
        }
    }
    if let Some(cap) = cfg.limits.monthly_tokens {
        if tokens >= cap {
            return Err(format!(
                "Monthly token limit reached ({tokens} of {cap}) — raise it in Settings → AI"
            ));
        }
    }
    Ok(())
}

// ── Local memory preflight ───────────────────────────────────────────────────
//
// Loading a local model that does not fit is not a slow path, it is an OOM
// that takes the machine down with it (measured the hard way: a 17 GB model
// alongside the sidecar's vision embedder on a 36 GB machine). So for local
// providers we ask how big the weights are and how much memory the machine
// could actually give them before issuing the request, and fall back or
// refuse.
//
// The subtlety is what "could give" means on macOS. `vm_stat`'s free pages
// are not it: the system keeps almost nothing free, compressing anonymous
// memory and evicting file cache on demand. Measured on the 36 GB dev
// machine while it was happily serving a 17.4 GB resident model, free +
// inactive + speculative + purgeable came to 2.9 GB — a figure that refuses
// every model in the library, which is exactly the false alarm this check
// used to raise. What actually takes a machine down is *wired* memory: pages
// the kernel cannot page out, which on Apple silicon is where GPU-resident
// model weights (and the sidecar's MPS embedder) live. Everything else is
// compressible or swappable, so only wired pages count against a model.

/// Weights need a little headroom for the KV cache and runtime. Measured:
/// a 16.5 GB Q4_K_M 27B sits at 17.4 GB resident with a 32k context — 1.05×.
const MODEL_MEM_FACTOR: f64 = 1.15;

/// Never plan to use the last of the machine.
const MEM_RESERVE: u64 = 2 * 1024 * 1024 * 1024;

/// Physical memory, from `sysctl hw.memsize`.
#[cfg(target_os = "macos")]
fn total_memory() -> Option<u64> {
    let out = crate::platform::command("sysctl")
        .args(["-n", "hw.memsize"])
        .output()
        .ok()?;
    String::from_utf8_lossy(&out.stdout).trim().parse().ok()
}

/// Memory the machine could hand a model right now: physical memory less the
/// wired pages and a reserve. Page size comes out of `vm_stat`'s own header —
/// it is 16 KB on Apple silicon, and assuming 4 KB miscounts by fourfold.
#[cfg(target_os = "macos")]
fn assignable_memory() -> Option<u64> {
    let total = total_memory()?;
    let out = crate::platform::command("vm_stat").output().ok()?;
    let text = String::from_utf8_lossy(&out.stdout);
    let mut page_size = 4096u64;
    let mut wired = 0u64;
    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("Mach Virtual Memory Statistics:") {
            if let Some(n) = rest.split("page size of ").nth(1) {
                if let Some(v) = n.split_whitespace().next().and_then(|v| v.parse().ok()) {
                    page_size = v;
                }
            }
        }
        if let Some(rest) = line.strip_prefix("Pages wired down") {
            if let Ok(v) = rest.trim_start_matches(':').trim().trim_end_matches('.').parse::<u64>() {
                wired = v;
            }
        }
    }
    (wired > 0).then(|| total.saturating_sub(wired * page_size + MEM_RESERVE))
}

#[cfg(windows)]
fn assignable_memory() -> Option<u64> {
    use windows_sys::Win32::System::SystemInformation::{GlobalMemoryStatusEx, MEMORYSTATUSEX};
    let mut status: MEMORYSTATUSEX = unsafe { std::mem::zeroed() };
    status.dwLength = std::mem::size_of::<MEMORYSTATUSEX>() as u32;
    (unsafe { GlobalMemoryStatusEx(&mut status) } != 0)
        .then(|| status.ullAvailPhys.saturating_sub(MEM_RESERVE))
}

#[cfg(not(any(windows, target_os = "macos")))]
fn assignable_memory() -> Option<u64> {
    None
}

/// On-disk size of an Ollama model, from its native `/api/tags`. The
/// OpenAI-compatible `/v1/models` carries no size, and LM Studio exposes
/// none at all — an unknown size is not an error, it just skips the check.
fn ollama_model_size(provider: &ProviderConfig, model: &str) -> Option<u64> {
    if provider.kind != "ollama" {
        return None;
    }
    let v = ollama_get(provider, "/api/tags")?;
    v["models"]
        .as_array()?
        .iter()
        .find(|m| m["name"].as_str() == Some(model))
        .and_then(|m| m["size"].as_u64())
}

/// Models Ollama currently holds resident, with what each occupies. Their
/// memory counts as available to a new model: Ollama evicts what it must to
/// make room, and a model already in this list needs nothing at all.
fn ollama_loaded(provider: &ProviderConfig) -> Vec<(String, u64)> {
    let Some(v) = ollama_get(provider, "/api/ps") else {
        return Vec::new();
    };
    v["models"]
        .as_array()
        .map(|ms| {
            ms.iter()
                .filter_map(|m| {
                    let name = m["name"].as_str()?.to_string();
                    Some((name, m["size_vram"].as_u64().or(m["size"].as_u64())?))
                })
                .collect()
        })
        .unwrap_or_default()
}

fn ollama_get(provider: &ProviderConfig, path: &str) -> Option<serde_json::Value> {
    if provider.kind != "ollama" {
        return None;
    }
    let url = format!("{}{path}", provider.base_url().ok()?);
    let text = ureq::builder()
        .timeout(MODELS_TIMEOUT)
        .build()
        .get(&url)
        .call()
        .ok()?
        .into_string()
        .ok()?;
    serde_json::from_str(&text).ok()
}

fn gb(bytes: u64) -> f64 {
    bytes as f64 / 1_073_741_824.0
}

/// Whether `model` plausibly fits right now. `None` means "cannot tell" and
/// is treated as fitting — never block a call on a missing measurement.
fn model_fits(provider: &ProviderConfig, model: &str) -> Option<(bool, u64, u64)> {
    let size = ollama_model_size(provider, model)?;
    let needed = (size as f64 * MODEL_MEM_FACTOR) as u64;
    let loaded = ollama_loaded(provider);
    // Already resident — it demonstrably fits, whatever the arithmetic says.
    if loaded.iter().any(|(name, _)| name == model) {
        return Some((true, needed, needed));
    }
    let reusable: u64 = loaded.iter().map(|(_, size)| size).sum();
    let available = assignable_memory()? + reusable;
    Some((needed <= available, needed, available))
}

/// Walk the preferred model then the fallback chain, in the user's order, and
/// take the first that can actually run: its provider still exists and, for a
/// measurable local model, its weights fit in free memory. Cloud providers and
/// unmeasurable local ones pass straight through.
///
/// A refusal names every candidate and why it was skipped — the alternative is
/// a user staring at "not enough memory" for a chain they thought was cloud.
pub fn resolve(cfg: &LlmConfig, preferred: &ModelRef) -> Result<Resolved, String> {
    let mut chain: Vec<&ModelRef> = vec![preferred];
    for f in cfg.fallbacks.iter().take(MAX_FALLBACKS) {
        if !chain.contains(&f) {
            chain.push(f);
        }
    }

    let mut skipped: Vec<String> = Vec::new();
    for candidate in chain {
        let Some(provider) = cfg.provider(&candidate.provider_id) else {
            skipped.push(format!("{} (its provider is no longer configured)", candidate.model));
            continue;
        };
        match model_fits(provider, &candidate.model) {
            None | Some((true, _, _)) => {
                if !skipped.is_empty() {
                    eprintln!(
                        "[oculus] llm: falling back to {} — skipped {}",
                        candidate.model,
                        skipped.join(", ")
                    );
                }
                return Ok(Resolved {
                    provider: provider.clone(),
                    model: candidate.model.clone(),
                });
            }
            Some((false, needed, available)) => skipped.push(format!(
                "{} (needs ~{:.1} GB, ~{:.1} GB available)",
                candidate.model,
                gb(needed),
                gb(available)
            )),
        }
    }

    Err(format!(
        "No configured model can run right now: {}. Free some memory — quit an app, or `ollama stop` a model you are not using — or add a smaller fallback in Settings → AI.",
        skipped.join("; ")
    ))
}

// ── Chat completions (streaming SSE) ─────────────────────────────────────────

pub struct StreamOutcome {
    /// The assistant message, ready to append to an OpenAI-shape history
    /// (includes tool_calls when the model made any).
    pub message: serde_json::Value,
    pub content: String,
    pub usage: Usage,
}

#[derive(Default)]
struct ToolCallAcc {
    id: String,
    name: String,
    arguments: String,
}

/// Blocking; run inside `spawn_blocking` (ureq is sync, like every other
/// outbound call in this crate). Streams deltas to `on_delta` as they arrive
/// and returns the assembled message plus usage.
pub fn chat_completion_stream(
    provider: &ProviderConfig,
    model: &str,
    messages: &serde_json::Value,
    tools: Option<&serde_json::Value>,
    mut on_delta: impl FnMut(&str),
) -> Result<StreamOutcome, String> {
    let url = provider.api_url("/chat/completions")?;

    let mut body = serde_json::json!({
        "model": model,
        "messages": messages,
        "stream": true,
        "stream_options": { "include_usage": true },
    });
    if let Some(t) = tools {
        body["tools"] = t.clone();
    }
    if provider.kind == "openrouter" {
        // Asks OpenRouter to report real cost in the final usage chunk.
        body["usage"] = serde_json::json!({ "include": true });
    }

    // Read timeout only — an overall timeout would kill long generations.
    let agent = ureq::builder()
        .timeout_connect(CONNECT_TIMEOUT)
        .timeout_read(READ_TIMEOUT)
        .build();
    let mut req = agent.post(&url).set("Content-Type", "application/json");
    if let Some(key) = provider.api_key() {
        req = req.set("Authorization", &format!("Bearer {key}"));
    }
    let resp = req.send_string(&body.to_string()).map_err(request_error)?;

    let reader = BufReader::new(resp.into_reader());
    let mut content = String::new();
    let mut tool_calls: Vec<ToolCallAcc> = Vec::new();
    let mut usage = Usage::default();

    for line in reader.lines() {
        let line = line.map_err(|e| format!("stream read: {e}"))?;
        let Some(data) = line.strip_prefix("data:") else { continue };
        let data = data.trim();
        if data == "[DONE]" {
            break;
        }
        // Skip keep-alives / non-JSON noise rather than aborting the stream.
        let Ok(chunk) = serde_json::from_str::<serde_json::Value>(data) else { continue };

        if let Some(u) = chunk.get("usage").filter(|u| u.is_object()) {
            usage.prompt_tokens = u["prompt_tokens"].as_i64().unwrap_or(0);
            usage.completion_tokens = u["completion_tokens"].as_i64().unwrap_or(0);
            usage.cost_usd = u.get("cost").and_then(|c| c.as_f64());
        }

        let delta = &chunk["choices"][0]["delta"];
        if let Some(text) = delta["content"].as_str() {
            if !text.is_empty() {
                content.push_str(text);
                on_delta(text);
            }
        }
        // Tool-call fragments arrive keyed by index; the arguments string is
        // split across chunks and must be concatenated.
        if let Some(calls) = delta["tool_calls"].as_array() {
            for tc in calls {
                let idx = tc["index"].as_u64().unwrap_or(tool_calls.len() as u64) as usize;
                if tool_calls.len() <= idx {
                    tool_calls.resize_with(idx + 1, ToolCallAcc::default);
                }
                let acc = &mut tool_calls[idx];
                if let Some(id) = tc["id"].as_str() {
                    acc.id = id.to_string();
                }
                if let Some(name) = tc["function"]["name"].as_str() {
                    acc.name.push_str(name);
                }
                if let Some(args) = tc["function"]["arguments"].as_str() {
                    acc.arguments.push_str(args);
                }
            }
        }
    }

    let mut message = serde_json::json!({ "role": "assistant", "content": content });
    if !tool_calls.is_empty() {
        message["tool_calls"] = tool_calls
            .iter()
            .map(|tc| {
                serde_json::json!({
                    "id": tc.id,
                    "type": "function",
                    "function": { "name": tc.name, "arguments": tc.arguments },
                })
            })
            .collect::<Vec<_>>()
            .into();
    }

    Ok(StreamOutcome { message, content, usage })
}

/// Surface the provider's error body (auth failures, bad model ids) instead
/// of just a status code.
fn request_error(e: ureq::Error) -> String {
    match e {
        ureq::Error::Status(code, resp) => {
            let body = resp.into_string().unwrap_or_default();
            let body = body.trim();
            if body.is_empty() {
                format!("provider returned HTTP {code}")
            } else {
                format!("provider returned HTTP {code}: {}", &body[..body.len().min(500)])
            }
        }
        other => format!("provider unreachable: {other}"),
    }
}

// ── Commands ─────────────────────────────────────────────────────────────────

#[tauri::command]
pub fn llm_set_api_key(provider_id: String, key: String) -> Result<(), String> {
    let key = key.trim();
    if key.is_empty() {
        return Err("empty key".into());
    }
    keychain(&provider_id)?.set_password(key).map_err(|e| e.to_string())
}

#[tauri::command]
pub fn llm_has_api_key(provider_id: String) -> bool {
    stored_api_key(&provider_id).is_some()
}

#[tauri::command]
pub fn llm_delete_api_key(provider_id: String) -> Result<(), String> {
    match keychain(&provider_id)?.delete_credential() {
        Ok(()) | Err(keyring::Error::NoEntry) => Ok(()),
        Err(e) => Err(e.to_string()),
    }
}

/// One entry of a provider's catalogue. Context and price are carried when the
/// provider reports them (OpenRouter does) — with hundreds of models listed,
/// the two numbers that decide the choice have to be visible while searching.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelInfo {
    pub id: String,
    pub name: Option<String>,
    pub context_length: Option<i64>,
    /// Prompt price in USD per million tokens.
    pub prompt_price_per_m: Option<f64>,
}

/// Browse one provider's catalogue. Not the same thing as the user's library:
/// this is the raw list to pick *from*, fetched on demand and never stored.
#[tauri::command]
pub async fn llm_list_models(provider_id: String) -> Result<Vec<ModelInfo>, String> {
    let pool = open_pool().await?;
    let cfg = load_config(&pool).await?;
    let provider = cfg
        .provider(&provider_id)
        .ok_or_else(|| format!("no provider '{provider_id}'"))?
        .clone();
    tauri::async_runtime::spawn_blocking(move || {
        let url = provider.api_url("/models")?;
        let agent = ureq::builder().timeout(MODELS_TIMEOUT).build();
        let mut req = agent.get(&url);
        if let Some(key) = provider.api_key() {
            req = req.set("Authorization", &format!("Bearer {key}"));
        }
        let text = req
            .call()
            .map_err(request_error)?
            .into_string()
            .map_err(|e| format!("models: unreadable response: {e}"))?;
        let v: serde_json::Value =
            serde_json::from_str(&text).map_err(|e| format!("models: bad response: {e}"))?;
        let mut models: Vec<ModelInfo> = v["data"]
            .as_array()
            .map(|arr| arr.iter().filter_map(model_info).collect())
            .unwrap_or_default();
        models.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(models)
    })
    .await
    .map_err(|e| e.to_string())?
}

fn model_info(m: &serde_json::Value) -> Option<ModelInfo> {
    // OpenRouter prices per token as a decimal string; a million-token figure
    // is the only one anyone reads.
    let prompt_price_per_m = m["pricing"]["prompt"]
        .as_str()
        .and_then(|p| p.parse::<f64>().ok())
        .map(|p| p * 1_000_000.0);
    Some(ModelInfo {
        id: m["id"].as_str()?.to_string(),
        name: m["name"].as_str().map(String::from),
        context_length: m["context_length"]
            .as_i64()
            .or_else(|| m["top_provider"]["context_length"].as_i64()),
        prompt_price_per_m,
    })
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TestOutcome {
    pub text: String,
    pub usage: Usage,
}

/// End-to-end smoke test, driven from Settings → AI: streams a short reply via
/// `llm-test-delta` events and records usage like any real call, so the budget
/// check and the ledger are exercised too. `model` targets one library entry —
/// with several providers configured, "does this one work" is a per-model
/// question. Omitted, it tests the chat default.
#[tauri::command]
pub async fn llm_test_prompt(
    app: AppHandle,
    prompt: String,
    model: Option<ModelRef>,
) -> Result<TestOutcome, String> {
    let pool = open_pool().await?;
    let cfg = load_config(&pool).await?;
    check_budget(&pool, &cfg).await?;
    let preferred = model
        .or_else(|| cfg.chat_model.clone())
        .ok_or("no model selected — pick one in Settings → AI")?;
    let resolved = resolve(&cfg, &preferred)?;

    let provider = resolved.provider.clone();
    let model2 = resolved.model.clone();
    let outcome = tauri::async_runtime::spawn_blocking(move || {
        let messages = serde_json::json!([{ "role": "user", "content": prompt }]);
        chat_completion_stream(&provider, &model2, &messages, None, |delta| {
            app.emit("llm-test-delta", delta).ok();
        })
    })
    .await
    .map_err(|e| e.to_string())??;

    record_usage(&pool, &resolved.provider.id, &resolved.model, "test", &outcome.usage, None)
        .await?;
    Ok(TestOutcome { text: outcome.content, usage: outcome.usage })
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UsageSummary {
    pub month_prompt_tokens: i64,
    pub month_completion_tokens: i64,
    pub month_cost_usd: f64,
    pub month_requests: i64,
}

#[tauri::command]
pub async fn llm_usage_summary() -> Result<UsageSummary, String> {
    let pool = open_pool().await?;
    let row = sqlx::query(
        "SELECT COALESCE(SUM(prompt_tokens), 0) AS pt,
                COALESCE(SUM(completion_tokens), 0) AS ct,
                COALESCE(SUM(cost_usd), 0.0) AS usd,
                COUNT(*) AS n
         FROM llm_usage
         WHERE created_at >= strftime('%Y-%m-01 00:00:00', 'now')",
    )
    .fetch_one(&pool)
    .await
    .map_err(|e| e.to_string())?;
    Ok(UsageSummary {
        month_prompt_tokens: row.get("pt"),
        month_completion_tokens: row.get("ct"),
        month_cost_usd: row.get("usd"),
        month_requests: row.get("n"),
    })
}
